#ifndef STATUS_H
#define STATUS_H

//Global status codes. This allows for error propogation through call chains
typedef enum
{
    SUCCESS = 0,

    NULL_POINTER_PASSED = -1,
    INVALID_ARGUMENT = -2,
    INDEX_OUT_OF_BOUNDS = -3,

    NO_SPACE = -11,
    INSUFFICIENT_ARRAY_PASSED = -12, //Array passed does not meet the size requirement of the function
    FREE_CHUNK_ACCESS_ATTEMPT = -13,
    DATA_OVER_FLOW = -14,
    DATA_SET_IS_EMPTY = -15,
    
    FILE_CHUNK_EXTENT_LIMIT_EXCEEDED = -21,
    CHUNK_DOES_NOT_BELONG_TO_FILE = -22,
    NOT_FOUND_CHUNKS_TERMINATED = -23,
    FILE_IS_EMPTY = -24,

    INVALID_OPERATION = -31,
    INVALID_ROOT_OPERATION = -32,
    ATTEMPTED_TO_DELETE_FOLDER_WITH_SUB_ENTRIES = -34,
    ATTEMPTED_TO_ENFORCE_CYCLIC_RELATION = -35,
    
    SEARCH_TARGET_NOT_FOUND = -41,
    PATH_IS_TOO_LONG = -42,
    PATH_IS_EMPTY = -43,
    
    IDENTIFIER_NOT_AVAILABLE = -51,
    IDENTIFIER_IS_TOO_LONG = -52,
    
    UNKNOWN_ENTRY = -61,
    UNINITIALISED_ENTRY = -62,
    
    RECURSIVE_OPERATION_LIMIT_EXCEEDED = -71,
    
    //Tests
    TEST_ASSERTION_FAILED = -101,
    
    //Meta
    IMPLEMENTATION_INCOMPLETE = -201,
    
    //Workspace
    EXPECTED_FOLDER_GOT_FILE = -301,
    EXPECTED_FILE_GOT_FOLDER = -302,

    INVALID_SAFE_MODE_OP = -311,

    //CMD parser and tokenizer
    TOO_MANY_ARGUMENTS = -401,
    TOO_MANY_OPTIONS = -402,
    TOO_MANY_TOKENS = -403,
    CMD_IS_TOO_LONG = -404,
    CMD_IS_EMPTY = -405,
    INVALID_CMD_FUNCTION = -406,
    INVALID_CMD_OPT = -407,

    //Input Handler
    READ_ERROR = -411,
    ATTEMPTED_TO_READ_AT_EOF = -412,
    INPUT_BUFFER_OVER_FLOW = -413,
    TOO_MANY_LINES = -414,
    INPUT_LINE_IS_TOO_LONG = -415,
    
    //Dispatcher
    COMMAND_FUNCTION_NOT_FOUND = -421,

    //CMD Executer
    CMD_TOO_FEW_ARGS = -431,
    CMD_TOO_MANY_ARGS = -432,
    CMD_TOO_FEW_OPTS = -433,
    CMD_TOO_MANY_OPTS = -434,
    CMD_UNKNOWN_OPT = -435,
    CMD_UNKNOWN_ARG = -436
} StatusCode;

#endif