#ifndef SETTINGS_H
#define SETTINGS_H

#define CHUNK_SIZE 8 //bytes
#define CHUNKS_AMOUNT 20

#define MAX_FILE_CHUNK_EXTENTS_AMOUNT 10

#define EOC_OPERATOR 0x1E

#define MAX_NAME_LENGTH 32 //(i.e file names and folder names)

#define MAX_SUB_FILES_AMOUNT 10
#define MAX_SUB_FOLDERS_AMOUNT 10

#define PATH_DELIMITER '/'
#define MAX_PATH_NODES_AMOUNT 10

#define MAX_FOLDER_DEPTH MAX_PATH_NODES_AMOUNT

#define VFS_MAX_FILES_AMOUNT 20
#define VFS_MAX_FOLDERS_AMOUNT 20

#endif